image: node:16

pipelines:
  branches:
    master:
        - step:
            name: Cache invalidation
            script:
              - pipe: atlassian/bitbucket-clear-cache:3.1.1
                variables:
                    BITBUCKET_USERNAME: $BITBUCKET_USER_NAME
                    BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                    CACHES: ["node"]
            condition:
              changesets:
                includePaths:
                  - package.json

        - step:
            name: Build project
            caches:
              - node
            script:
              - npm install
              - npm run build
              - npm set //$NPM_REGISTRY/:_authToken $NPM_AUTH_TOKEN
        - parallel:
            - step:
                name: Publish components
                caches:
                  - node
                script:
                  - cd dist/applicature/components
                  - npm pack .
                  - npm publish --access public
            - step:
                name: Publish styles
                caches:
                  - node
                script:
                  - cd dist/applicature/styles
                  - npm pack .
                  - npm publish --access public