image: node:16

pipelines:
  default:
    - step:
        name: Code linting
        script:
        - npm install
        - npm run build
        - cd dist/ngx-web3-components
        - npm pack .
        - npm set //https://registry.npmjs.org/:_authToken $NPM_AUTH_TOKEN
        - npm adduser
        - npm publish --access public
        caches:
          - node
