image: node:16

pipelines:
  default:
    - step:
        name: Code linting
        script:
        - npm install
        - npm run build
        - cd dist/ngx-web3-components
        - npm pack .
        - echo "_auth = $NPM_AUTH_TOKEN" > ~/.npmrc
        - echo "email = $NPM_EMAIL" >> ~/.npmrc
        - npm adduser
        - npm publish --access public
        caches:
          - node
