image: node:16

pipelines:
  default:
    - step:
        name: Code linting
        script:
        - npm set //https://$NPM_REGISTRY/:_authToken $NPM_AUTH_TOKEN
        #- echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
        - ln -sf ~/.npmrc .
        - npm install
        - npm run build
        - cd dist/ngx-web3-components
        - npm pack .
        - npm publish --access public
        caches:
          - node
