image: node:16

pipelines:
  default:
    - step:
        name: Code linting
        script:
        - npm install
        - npm run build
        - cd dist/ngx-web3-components
        - npm pack .
        - |
          npm adduser <<!
          $NPM_USERNAME
          $NPM_PASSWORD
          $NPM_EMAIL
          !
        - npm publish --access public
        caches:
          - node
